### ISSUE TITLE
[1.16.5] Support for Bamboo Blocks not working, game crashes.

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/CeilingTorch#48] opened 2021-08-14 00:50 UTC
When booting up the game with Bamboo Blocks + Ceiling Torch, the game crashses.

Minecraft: 1.16.5
Forge: 36.2.2
Bamboo Blocks: 3.0.0 | https://www.curseforge.com/minecraft/mc-mods/bamboo-blocks/files/3416596
Ceiling Torch: 1.13.3 | https://www.curseforge.com/minecraft/mc-mods/ceiling-torch/files/3417027

Crash-Report: https://gist.github.com/Gbergz/71d7c6f160898969e16ba6dcb5a52f0a

**-** Gbergz

**Comment by RandomBlobbles** [comment] 2021-08-14 00:51
We made a crash report with bamboo blocks at the same time lmao

**Comment by Gbergz** [comment] 2021-08-14 00:52
> We made a crash report with bamboo blocks at the same time lmao

That is hilarious, wow. Timing!

**Comment by bl4ckscor3** [comment] 2021-08-14 09:00
Duplicate of #47 😄

**Closed as completed by bl4ckscor3** 2021-08-14 09:00 UTC
Labels: duplicate
